### ISSUE TITLE
Add https protocol support

### ISSUE THREAD

**Issue by query-string** [saberespoder/contenido#110]
At the moment it is impossible to reach any of pages by HTTPS, only HTTP copies are available. It is very important to provide HTTP access because Google penalizes non-https websites.

**Comment by query-string** [comment]
I _suddenly_ found out another reason to push on this issue – custom maintenance mode page that I recently mentioned in [#dev-team Slack channel](https://saberespoder.slack.com/archives/C242Z66SV/p1516788871000393) is now available on http://contenido.saberespoder.com/maintenance.html but... it won't be rendered because Heroku replaces all pages in maintenance mode by HTML with iframe and when iframe source protocol is different from the main page protocol (https -> http in our case) – the page in iframe is blocked by browser.

**Comment by etavenn** [comment]
closed because of transition to VP webiste
