### ISSUE TITLE
SEO: add keywords and description for a project

### ISSUE THREAD

**Issue by skatkov** [saberespoder/contenido#12]
After @stan2020 will provide all the needed information - implement it in code.

**Comment by stan2020** [comment]
Description:  SABEResPODER te ayuda prosperar en los EEUU, con recursos y contestas personalizadas a tus preguntas sobre inmigración, educación, finanzas, salud y otros asuntos importantes.  Tu causa es nuestra causa!

Keywords:
Inmigracion, ciudania, preguntas, articulos, derechos, finanzas, salud, educacion, comunidad, consulado, visa, pasaporte, estados unidos, informacion, ofertas, viviendo en los estados unidos, trabajar, trabajo, impuestos, taxes, embajada, el salvador, mexico, guatemala, informacion gratuita, medicamentos, farmacias, farmasep, descuentos, encuestas

**Comment by query-string** [comment]
Resolved by PR #23
