### ISSUE TITLE
Improve footer

### ISSUE THREAD

**Issue by skatkov** [saberespoder/contenido#2]
Copy pages from old sepcontent page, to new sepcontent project:
about -> http://about.saberespoder.com/about-us/
remove 'Corporate'
home - replace to 'saberespoder' and link to saberespoder.com
'legal' -> https://sepcontent.herokuapp.com/tnc
remove 'help' 

Currently footer is full page width, with should match with all the content of the page.
<img width="960" alt="screen shot 2017-03-09 at 21 12 02" src="https://cloud.githubusercontent.com/assets/544377/23766364/3182c7ca-050d-11e7-94b9-8bd9b1e2b23b.png">

**Comment by query-string** [comment]
Resolved by PR #24
