### ISSUE TITLE
SEO: get rid of multiple URls for identical articles

### ISSUE THREAD

**Issue by query-string** [saberespoder/contenido#22]
I have recently come across one issue on Content Platform that could possibly affect search engines ranking of articles there...

It turns out that some articles (I guess all of articles that belong to more than one category) appear with different URLs, e.g.:
https://content.saberespoder.com/articulos/educaci%C3%B3n/tramite-su-acta-de-nacimiento-sin-salir-del-pais
https://content.saberespoder.com/articulos/inmigraci%C3%B3n/tramite-su-acta-de-nacimiento-sin-salir-del-pais

As you can see, the content of these articles is 100% equal but pages have different URLs. AFAIK in such cases, search engines consider pages with different URLs as duplicates (even though the content is unique out of the website) and it might affect pages ranking in a negative manner. 

**[Just a quick note about content duplication and its consequences](https://moz.com/learn/seo/duplicate-content)**

As long as we have those URLs indexed in our current Content Platform I tend to keep this scheme as is for the new one, but I would highly recommend to get rid of them, have one unique URL for each unique article thus reducing pseudo duplication. 

We have had a quick chat with @tzinchenko in Slack, where she explained that articles could have many categories indeed and the first category is considering as a default. Thereby, we could easily get rid of trash URLs changing permalink scheme in this way: `https://content.saberespoder.com/articulos/#{MAIN_CATEGORY}/#{ARTICLE_TITLE}` (articles still will be visible in their category pages, but have unique URLs).

**Comment by FanaHOVA** [comment]
👍 Sounds good to me, since the categories will still be listed in the article we shouldn't lose search hits either since they are in the page content.

**Comment by stan2020** [comment]
If we're saying we'll eliminate all but one version of identical articles, I completely agree.  But please redirect the killed URLs to the lone survivor so that we don't lose whatever SEO traffic was going to those ones we're offing.

**Comment by skatkov** [comment]
@stan2020 out of all the articles that we have only 28 are indexed by google. I don't understand what are you worrying about.

**Comment by stan2020** [comment]
@skatkov more than 28 articles show up in search results, despite only 28 being officially indexed.  I believe it's around 12,000:  https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=site:www.saberespoder.com&start=0
I think that, as a rule, we should redirect when we kill a page -- esp. when there's an identical survivor, but happy to discuss.
