### ISSUE TITLE
Please decrease social network overdose

### ISSUE THREAD

**Issue by skatkov** [saberespoder/contenido#46]
<img width="1013" alt="screen shot 2017-04-24 at 18 18 04" src="https://cloud.githubusercontent.com/assets/544377/25344330/7a404600-291a-11e7-983f-cfb6dd9cbc95.png">

This is a bit too much, can we just leave facebook and twitter?

**Comment by query-string** [comment]
Sure thing we could. I would insist on leaving the print button as well though.

**Comment by query-string** [comment]
@skatkov done. Does it feel better in this way?

![image](https://cloud.githubusercontent.com/assets/160712/25393476/bd19035e-2a05-11e7-9c7d-3e0fe44ab1c6.png)

**Comment by skatkov** [comment]
@alex I'm not sure about printing button? it looks like every browser has 'print' button. Why do you think it's necessary ?

**Comment by query-string** [comment]
@skatkov I predicted this question and I have a feeling that only more or less "advanced" users might be aware of printing functionality. On the other hand – this button cries out about this option so it could prompt the end user to print the page ).
It is not like this button is really necessary but it could save just a couple of seconds to someone and it doesn't cost us anything.

**Comment by query-string** [comment]
@skatkov please, let me know if you are eventually OK about that extra print button or against it in principal – I'm good to go with either option.

**Comment by tzinchenko** [comment]
Personally I agree with the first version (and I liked that all sharing worked). Internet doesn't include only Facebook and Twitter. 
For example, I myself don't use Twitter at all, but use Linkedin. And we just deleted Linkedin button.
Let's ask @etavenn though.

**Comment by skatkov** [comment]
@query-string let's leave for now print, let's see if it sticks ;-)

**Comment by etavenn** [comment]
Of the options listed there, I know that FB is the most used. Is the pencil option SMS? According to our surveys, twitter is not used a lot.

Are these the only options available? Can we add Whatsapp?

My opinion is FB, Twitter(why not, let's give it a try), SMS, Whatsapp (if available). We could also do print.

**Comment by skatkov** [comment]
pencil option is livejournal, mostly popular in Russian internet.

**Comment by etavenn** [comment]
ah ok. yeah let's not add livejournal then.

**Comment by query-string** [comment]
@etavenn full list of available options attached below. And holy cow – Whatsapp exists there indeed!

![image](https://cloud.githubusercontent.com/assets/160712/25935788/f59f5016-364e-11e7-9b99-e7c832f44339.png)

**Comment by etavenn** [comment]
@query-string is changing the channel buttons something a non-techie can do?

**Comment by query-string** [comment]
@etavenn sure thing, there is a control panel on sharethis.com from where this screenshot has been taken, I'll send you credentials over DM

**Comment by etavenn** [comment]
thank you @query-string :)
