### ISSUE TITLE
Attach legit authors to all of articles (degrade Alexo Rodriguez)

### ISSUE THREAD

**Issue by query-string** [saberespoder/contenido#49]
> @etavenn[ in comments to #2194](https://github.com/saberespoder/inboundsms/issues/2194#issuecomment-298481277): 
All content appears to be written by Alexo Rodrigues (this is something Admin changes as well, right? If so, can we add a different default name? Lot's of work to change the editor name one-by-one)

To resolve this issue, I would approach it in this way:
1. _On the Contentful side_ – add a new content type called `Author`. This content type should have following fields: first name, last name, photo, default.
2. _On the Contentful side_ – associate `Article` content type with `Author` content type so each article can be assigned only to one author.
3. _On the Contentful side_ – create one or several authors, one of them marked as `default`. As I understand – it is barely possible to trace actual authorship for existent articles so we are relatively flexible to invent whoever we want (either real people from the team or imaginary characters).
4. Randomly assign authors for all of the articles. It cold be done just by single API call on our side.
5. By default, all of the new articles will be associated with author marked as default, but any of authors could be selected instead.

I'm going to convert Alexo Rodriguez to Contentful Article entry, marked it as default and from this point editors will be able to rename this entry however they want. Also, editors will be more than welcome to create several new semi-real authors – in will add some diversity and in this way articles could feel a bit more trusted.

@etavenn @stan2020 I hope you won't mind if I involve you for the stage 3 (once Author model is ready)?

**Comment by stan2020** [comment]
@query-string sounds like a good plan.  happy to jump in whenever you need me.  

i'm just trying to decide whether it's better to use imaginary author names or something like "SABEResPODER Equipo Editorial".  publishers sometimes get dinged for inventing writers.  it can come off as sketchy.  either way, your approach should work b/c "SABEResPODER Equipo Editorial" could just be one of the names we assign, right?

**Comment by etavenn** [comment]
@query-string so basically @stan2020 and I could change the default editor name to "SABEResPODER Equipo Editorial" (step 3)?

We can also modify the other authors, right? We would do this once the platform goes live?

**Comment by query-string** [comment]
@etavenn yep, almost right – I think it will be better to perform all of
steps before running the platform ) I'll try to implement this
functionality earlier tomorrow and ping you and Stan so you could take a
look how it work in life

**Comment by etavenn** [comment]
@query-string sounds good!

**Comment by query-string** [comment]
@stan2020 @etavenn hi guys! Just letting you know that article authors are editable now, mr. Rodriguez still is a default author for all articles, but you are able to change this entry however you want https://app.contentful.com/spaces/oa34n7smn7kt/entries/4Xs1H7GKjuC6Kskk4K2I4c (please, keep author photo grayscale). You could also create more authors if you and assign them to selected articles.

**Comment by etavenn** [comment]
@query-string thanks! Alexoo Rodriguez will be missed.

Why greyscale?

**Comment by query-string** [comment]
@etavenn it hard to explain why it feels that colorful user pics work not so good in this case (I've tried several with Alexo already)... I think it happens because user pic is merely additional information comparing with other data in this block (title, categories, author name) but if we make it colorful it undeservedly stands out comparing to others.

**Comment by etavenn** [comment]
weird. out of curiosity, what happens when we change it to colorful?

**Comment by query-string** [comment]
@etavenn well, I'm not really insisting :D Just try to set colorful pic and see if it fits. Maybe it's only mine perception perceives them as color spots )

**Comment by etavenn** [comment]
@query-string got it! I think we are going to use this:

![screenshot 2017-05-11 at 4 50 04 pm](https://cloud.githubusercontent.com/assets/16109106/25976452/e83a884e-3669-11e7-89eb-b8a469522f3a.png)

**Comment by query-string** [comment]
@etavenn 
![image](https://cloud.githubusercontent.com/assets/160712/25993140/44e84a80-3733-11e7-8cc7-d71db745bc68.png)
