### ISSUE TITLE
Make `About us` section editable

### ISSUE THREAD

**Issue by query-string** [saberespoder/contenido#50]
> @etavenn [in comment to #2194](https://github.com/saberespoder/inboundsms/issues/2194#issuecomment-298481277)
Copy in the "about us" section is not current (I believe Admins will be able to edit that themselves, right?)

In fact, this section is not editable from Contentful at the moment. To achieve requested result we will have to add a new `Page` content type, make content platform support these pages and update _About us_ on Contentful. I'll ping @etavenn and @stan2020 here once it will be available for edit.

**Comment by stan2020** [comment]
Just saw I was assigned this one.  Is the About page editable now?

**Comment by query-string** [comment]
@stan2020 yes sir, if you have access to Contentful, editor will be available on https://app.contentful.com/spaces/oa34n7smn7kt/entries/2rKqKmw6yc0kEai6I84ge2
When you finish editing just press `Publish changes` button and changed page will be uploaded to http://sepcontent.s3-website-us-east-1.amazonaws.com/about-us/ within 2-3 minutes (you could monitor platform channel in Slack – it usually shows current build status with label `via API by SEPTechMain`).

**Comment by etavenn** [comment]
Thank you @query-string . Will notify the team so they can start editing it.

**Comment by query-string** [comment]
@etavenn cool! It would be great if we could handle this issue asap – it is one of the most important ones and can potentially block this release. Stas is eager to run content platform during this iteration and you know... sometimes I think he is more dangerous person than my landlady 😁

**Comment by stan2020** [comment]
Going through and fixing broken links from Tatiana's list now.  Couple questions/issues -- and lmk if either should be its own github:
- When I tried to using the hyperlink button in the top menu to hyperlink the words "esta pagina" in [the edit view of this article](https://app.contentful.com/spaces/oa34n7smn7kt/entries/3nd6c3DMhimMiUSCiEOSku), it seems to create a new paragraph with those words at the beginning.  What did I do wrong?
- Right now it looks like there's the Editor view with all of the code showing and then another Preview view, which you can't actually work in.  It's difficult working in the code version b/c of all the tags and lack of formatting.  Is there another view that's at least semi-wysiwyg that I don't see?

**Comment by etavenn** [comment]
@query-string 
>Stas is eager to run content platform during this iteration 

Can we edit the page during the process or even after? I'm afraid the copy might not be ready this week.

**Comment by stan2020** [comment]
Yes, there's no need to hold up launch for the copy on the About Us page.  The beauty of the web -- and the new platform -- is that we can make changes at any time.  I should have a draft today, but it'll take at least a few days to get to a final version.   We're not doing a big public launch or anything, that page gets extremely few visitors and living with it as is (I already chopped off the most outdated section at the end) for another week shouldn't create any issues.

**Comment by etavenn** [comment]
@query-string it's also my understanding that we can edit this page at any point and it won't delay the launch of content page. If you see any reason why it would let us know. Otherwise please don't wait for changes on this page to get the rest of the platform ready to launch. :)
