### ISSUE TITLE
Translate English labels to Spanish

### ISSUE THREAD

**Issue by query-string** [saberespoder/contenido#51]
Initially, @etavenn requested only `All` tab translation [here](https://github.com/saberespoder/inboundsms/issues/2194), but I wonder if other strings should be translated accordingly.

1. "All" tab is in English. Change to "Index"
2. Prev/next pagination
3. Home, About in footer
4. Related articles block

If I'm right and those strings have to be translated as well – I'd be appreciated if you could tell me how to handle 2-4 better @etavenn @stan2020

**Comment by stan2020** [comment]
Prev/next pagination:  pagina anterior (previous page), siguiente página (next page)
Home, About in footer:  Home>Inicio, About>Quienes Somos 
Related articles block:  Contenido Relacionado

**Comment by tzinchenko** [comment]
Verified on development
