### ISSUE TITLE
Content Platform v1 extinction plan

### ISSUE THREAD

**Issue by query-string** [saberespoder/contenido#53]
One of the main reasons of Content Platform v2 existence is our urgent need to reduce database workload on the expense of moving dynamically generated pages to the static form (and moving out from our servers as an extra benefit). On the other hand, as @stan2020 and @etavenn have mentioned repeatedly – we will need to keep articles and comments accessible for internal usage (and as a backup in case if we will want to use them in the future somehow).

In my opinion, both options are available, implementation is easy enough and we just have to prepare a list of possible steps. I'd like to propose one and looking forward to seeing your comments @skatkov @etavenn @stan2020 

1. Assign a new domain name for sepcontnet bucket as discussed in #11 
2. Once all issues from [MVP launch](https://github.com/saberespoder/sepcontent-v2/milestone/1) milestone are resolved – gracefully redirect all of the calls from content.saberespoder.com to the new domain. To be honest – I'm not 100% sure that if it will be better to keep a chain of redirects (i.e. saberespoder.com -> content.saberespoder.com -> comunidad.saberespoder.com) than just change content.saberespoder.com to comunidad.saberespoder.com wherever we have it hard coded.
3. Reduce the number of sepcontent workers on Heroku, disable autoscaling, sidekiq and add-ons like Papertrail and Elasticsearch. It will help us to cut a maintenance price drastically. 
4. Add HTTP basic auth for https://content.saberespoder.com thereby it will stay alive, but not accessible from the World – only people who know login/password pair will be available to review articles/comments (use this old instance as an archive).

**Comment by stan2020** [comment]
Works for me.  Will the archive be searchable?

**Comment by etavenn** [comment]
sounds good to me, @query-string ! 

A future use that comes to mind is showing users what articles they've commented in the past and the answer they received by us. This data will still be found in our DB, right? I guess this would also answer @stan2020 's question I think
