### ISSUE TITLE
Adding ability to preview full article

### ISSUE THREAD

**Issue by skatkov** [saberespoder/contenido#68]
requested by @stan2020 

He needs a way to preview full article (with image). I found this documentation:
https://www.contentful.com/r/knowledgebase/setup-content-preview/

**Comment by query-string** [comment]
How to test this feature:
1. Open any article with `Draft` status (I used [this one](https://app.contentful.com/spaces/oa34n7smn7kt/entries/69sgMDubg4oS4eQaQS2Kwk) for testing) on Contentful (_sepcontent_ space)
2. Change anything in the article, make sure saving completed (status block in the right top corner should content `Last saved a few seconds ago` string)
3. Press `Open Preview` button underneath the `Status` block
4. You will see the article as it will be generated after publication

**Comment by Kefirka** [comment]
1. Author isn't changed

Open any article to edit
Remove current author
Add new author http://prntscr.com/if4sw4
Wait few seconds while changes are applied
Tap on Preview article button

Actual result - removed author is shown http://prntscr.com/if4u22
Expected result - new author is shown

2. Error appears when user tries to preview article with inactive category

Open any article to edit
Tap on Create category button
Fill Title
Do not select status and return back to the article body
tap on Preview article button

Actual result - error appears http://prntscr.com/if4pgy
Expected result - article is shown correctly

The same situation for buttons without some data

3. Timemark isn't updated after adding category/button

Open any article for editing
Tap on Create button link
Create new button
return back to the article body

Actual result - timemark isn't updated http://prntscr.com/if4wsy 
Expected result - timemark is actual

**Comment by query-string** [comment]
1 – ✔️ 
2 – ✔️ 
3 – We are not able to affect Contentful behaviour so if time mark isn't updated after adding category/button we can only guess why Contentful engineers implemented it in this way. However – I tried to reproduce described bug and was unable to do it – if I create new category/button, no matter with attributes or not, it does update time mark 🤷‍♂️

**Comment by Kefirka** [comment]
1 - verified
2 - not fixed http://prntscr.com/igqu9u

**Comment by Kefirka** [comment]
4.
Open article for editing
Add existing category http://prntscr.com/igqysa
Tap on Preview button

actual result - there is no just added category 
Expected result - just added category is shown http://prntscr.com/igqz4t

5.
Open article to edit
Set Display questions widget as Yes http://prntscr.com/igqzfj
Tap on Open preview button

Actual result - Question widget isn't shown http://prntscr.com/igqzsi
Expected result - Question widget is shown

**Comment by query-string** [comment]
4 – despite the fact that FarmaSEP category is available for picking, this category has `inactive` status thus not displayed. To confirm that just select any other existing category which was published.
5 – ✔️

**Comment by Kefirka** [comment]
All fixed for dev!
